# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-10-04 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_update_registered_slide_types_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="slidetemplate",
            name="parent_template",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a suborg template, reference to the global template it was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suborg_copies",
                to="app.slidetemplate",
            ),
        ),
        migrations.AddField(
            model_name="slidetemplate",
            name="suborganisation",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this template is only available to branches in this suborganisation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slide_templates",
                to="app.suborganisation",
            ),
        ),
    ]
