# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-10-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_slidetemplate_parent_template_and_more"),
    ]

    operations = []
