# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-10-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_change_aspect_ratios_to_single_ratio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slidetemplate",
            name="accepted_aspect_ratios",
        ),
        migrations.AddField(
            model_name="slidetemplate",
            name="aspect_ratio",
            field=models.CharField(
                default="16:9",
                help_text='The aspect ratio for this template, e.g. "16:9", "4:3", "9:16"',
                max_length=10,
            ),
        ),
    ]
