# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-10-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_remove_slidetemplate_accepted_aspect_ratios_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displaywebsite",
            name="aspect_ratio",
            field=models.CharField(
                default="16:9",
                help_text='The aspect ratio for this display screen, e.g. "16:9", "4:3", "9:16"',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="displaywebsitegroup",
            name="aspect_ratio",
            field=models.CharField(
                default="16:9",
                help_text='The aspect ratio for this display group, e.g. "16:9", "4:3", "9:16". Only displays with matching aspect ratios can be added to this group.',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="slideshowplaylist",
            name="aspect_ratio",
            field=models.CharField(
                default="16:9",
                help_text='The aspect ratio for this playlist, e.g. "16:9", "4:3", "9:16". All slideshows in this playlist must have the same aspect ratio.',
                max_length=10,
            ),
        ),
    ]
