# Generated by Django 5.2.5 on 2025-10-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_displaywebsite_aspect_ratio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displaywebsite",
            name="uid",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
