# Generated by Django 5.2.5 on 2025-10-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_displaywebsite_uid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="branch",
            unique_together={("suborganisation", "name")},
        ),
    ]
