# Generated by Django 5.2.5 on 2025-11-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_customcolor_customfont_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customcolor",
            options={"ordering": ["organisation", "position", "name"]},
        ),
        migrations.AlterModelOptions(
            name="customfont",
            options={
                "ordering": ["organisation", "position", "name"],
                "verbose_name": "Custom Font",
                "verbose_name_plural": "Custom Fonts",
            },
        ),
    ]
