# Generated by Django 5.2.5 on 2025-12-08 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_slideshow_slidetemplate_islegacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSlideTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slideData", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "previewWidth",
                    models.IntegerField(
                        default=1920,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "previewHeight",
                    models.IntegerField(
                        default=1080,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "aspect_ratio",
                    models.CharField(
                        default="16:9",
                        help_text='The aspect ratio for this template, e.g. "16:9", "4:3", "9:16"',
                        max_length=10,
                    ),
                ),
                (
                    "isLegacy",
                    models.BooleanField(
                        default=False,
                        help_text="Legacy templates stay on the fixed 200x200 grid instead of per-pixel cells",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
