# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-12-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_organisation_uri_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("org_admin", "Organisation Admin"),
                    ("org_user", "Organisation User"),
                    ("suborg_admin", "Suborganisation Admin"),
                    ("branch_admin", "Branch Admin"),
                    ("employee", "Employee"),
                ],
                max_length=20,
            ),
        ),
    ]
