# SPDX-FileCopyrightText: 2025 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2025-12-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_alter_organisationmembership_role"),
        ("app", "0047_alter_globalslidetemplate_thumbnail_url"),
    ]

    operations = []
