# Generated by Django 5.2.5 on 2026-01-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_rename_globalslidetemplate_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slidetemplate",
            old_name="isLegacy",
            new_name="is_legacy",
        ),
    ]
