# Generated by Django 5.2.5 on 2026-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_rename_islegacy_slidetemplate_is_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="COMPLETED",
                help_text="Status of background processing (e.g. PDF conversion).",
                max_length=20,
            ),
        ),
    ]
