# Generated by Django 5.2.5 on 2026-01-22 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_document_processing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="slidetemplate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slidetemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
