# Generated by Django 5.2.5 on 2026-01-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_document_processing_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencySlideshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this emergency slideshow is currently active.",
                    ),
                ),
                (
                    "display_website_groups",
                    models.ManyToManyField(
                        help_text="Display groups affected by this emergency slideshow.",
                        related_name="emergency_slideshows",
                        to="app.displaywebsitegroup",
                    ),
                ),
                (
                    "slideshow",
                    models.ForeignKey(
                        help_text="Slideshow that overrides normal scheduling when active.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_slideshows",
                        to="app.slideshow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Slideshow",
                "verbose_name_plural": "Emergency Slideshows",
            },
        ),
    ]
