# Generated by Django 5.2.5 on 2026-01-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_emergencyslideshow"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideshow",
            name="is_emergency_slideshow",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
