# Generated by Django 5.2.5 on 2026-03-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_slidetemplate_created_at_slidetemplate_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textformattingsettings",
            name="allow_font_weight",
        ),
    ]
