# SPDX-FileCopyrightText: 2026 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2026-03-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0055_slidetemplate_created_at_slidetemplate_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredslidetypes",
            name="slide_type_id",
            field=models.IntegerField(
                choices=[
                    (1, "DDB Events API"),
                    (3, "Newsfeed with Image"),
                    (4, "Dreambroker"),
                    (5, "Newsticker"),
                    (6, "Speed Admin"),
                    (7, "Clock"),
                    (8, "DR Streams"),
                    (9, "KMD Foreningsportalen"),
                    (10, "Frontdesk LTK Borgerservice"),
                    (11, "WinKAS"),
                    (12, "Date"),
                ],
                help_text="Slide type that matches the frontend slide type system",
            ),
        ),
    ]
