# Generated by Django 5.2.5 on 2026-03-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_alter_registeredslidetypes_slide_type_id"),
        ("app", "0056_remove_textformattingsettings_allow_font_weight"),
    ]

    operations = []
