# SPDX-FileCopyrightText: 2026 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: AGPL-3.0-only
# Generated by Django 5.2.5 on 2026-03-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_merge_20260311_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredslidetypes",
            name="slide_type_id",
            field=models.IntegerField(
                choices=[
                    (1, "DDB Events API"),
                    (3, "Newsfeed with Image"),
                    (4, "Dreambroker"),
                    (5, "Newsticker"),
                    (6, "Speed Admin"),
                    (7, "Clock"),
                    (8, "DR Streams"),
                    (9, "KMD Foreningsportalen"),
                    (10, "Frontdesk LTK Borgerservice"),
                    (11, "WinKAS"),
                    (12, "Date"),
                    (13, "DDB Opening hours"),
                ],
                help_text="Slide type that matches the frontend slide type system",
            ),
        ),
    ]
